# Generated by Django 2.1.5 on 2019-03-20 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltenant',
            name='tn_contact',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must\n                              be entered in the format: \n                            '+999999999'. Up to 13 digits\n                             allowed.", regex='^\\+?1?\\d{10,13}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='tbltenant',
            unique_together={('tn_contact', 'tn_agent')},
        ),
    ]
