# Generated by Django 2.1.5 on 2019-04-10 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20190320_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrentcollection',
            name='rc_agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
